name: Test
on:
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Git, Node.js, & NPM
        run: |
          sudo apt-get -y install nodejs
          sudo apt-get -y install npm
      - name: Prepare Repository
        run: |
          npm install
      - name: Run Tests
        run: npm test
